remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Welcome to my humble site
description: On this site you can find Frame Generation Mods, Piracy Related Stuff, Mod Menus
